# Generated by Django 4.2.1 on 2023-05-25 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Plante', 'Plante'), ('Feu', 'Feu'), ('Eau', 'Eau'), ('Insecte', 'Insecte'), ('Normal', 'Normal'), ('Combat', 'Combat')], max_length=10)),
                ('niveau', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'pokemons',
            },
        ),
    ]
